### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kirbywon13** [patmagauran/ForzaDualSense#1]

**Comment by patmagauran** [comment]
This program is very simple, and if everything is setup correctly it should just work. Could you run the program with `--verbose` i.e. `ForzaDualSense.exe --verbose` This will tell me if it is receiving data from forza or not. 

Another thing to try is to *Temporarily* disable your system firewall to see if that is causing issues.

Also let me know the following details:
- OS Version and Build
- Forza Edition
- How are you running Forza(Steam, Xbox, etc.)

**Comment by joboyx** [comment]
This happened to me, I thought it was not working. I missed to turn on DATA OUT.

Just make sure to follow this:
![image](https://user-images.githubusercontent.com/920888/151834632-1de5828d-3d04-4af4-9ce8-a14ef6b136a6.png)

But before making this work, make sure that DualSenseX is working for your controller.

Thanks @patmagauran for working on this. Kudos!
