### ISSUE TITLE
Does this only enable adaptive trigger? Can a method like this be used for haptic feedback as well?

### ISSUE THREAD

**Issue by DamianPereira** [patmagauran/ForzaDualSense#9]
According to dualsensex page: 

> Game Mods with DSX can add support for adaptive trigger and haptic feedback. Use these mods to get the best gaming experience playing with your PS5 DualSense controller. 

And this mod is linked, but this only supports adaptive triggers right?

**Comment by patmagauran** [comment]
Yes, this only provides hooks for adaptive triggers.
